version: '3'

services:
  postgres:
    build:
      context: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
  redis:
    build:
      context: cache
    ports:
      - "6379:6379"
  shortener:
    build:
      dockerfile: src/main/docker/Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis